### ISSUE TITLE
job processor can't interpret passSubJacobianRankTask

### ISSUE THREAD

**Issue by falquaddoomi** [falquaddoomi/disting#3]
Output from processor:

```
Starting job 32...
 => Inside input processor!
 => completed laplaceTools.calcQ
 => completed laplaceTools.calcR
 => completed laplaceTools.calcTF
 => completed laplaceTools.getOrderedKeys
 => completed laplaceTools.calcJacobian
 => completed laplaceTools.calcRank
 => completed graphModel.graphModel
DONE MAKING ORIG MODEL
4
6
my original model graph (transposed)
[[ 1.  0.  0.  1.]
 [ 1.  1.  0.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  1.]]
my original model edges
[(0, 0), (0, 3), (1, 0), (1, 1), (2, 1), (2, 2), (3, 2), (3, 3)]
number of candidates: 8008
num of candidates left after graph properties checked: 411 out of 8008
the alphas: [[0, 1, 2, 3, 4]]
the betas: [[0, 1, 2]]
num of candidates left alpha betas checked: 411 out of 8008
num of candidates left after calc rank full jacobian: 357 out of 8008
About to compute laplaceTools.reducedJacMat()...
About to compute laplaceTools.calcAllSubranks()...
About to process candidates (distributed: True)...
Traceback (most recent call last):
  File "/home/faisal/projects/disting/interface/management/commands/processor.py", line 101, in handle
    result = computation.main.processInput(job.makeInput(), notify=lambda x: logger_notify(x, job))
  File "/home/faisal/projects/disting/computation/main.py", line 407, in processInput
    result = passSubJacobianRankTask.get()
  File "/home/faisal/projects/disting/.venv/local/lib/python2.7/site-packages/celery/result.py", line 512, in get
    interval=interval, callback=callback)
  File "/home/faisal/projects/disting/.venv/local/lib/python2.7/site-packages/celery/result.py", line 565, in join
    interval=interval)
  File "/home/faisal/projects/disting/.venv/local/lib/python2.7/site-packages/celery/result.py", line 151, in get
    interval=interval)
  File "/home/faisal/projects/disting/.venv/local/lib/python2.7/site-packages/celery/backends/base.py", line 177, in wait_for
    raise result
ValueError: invalid literal for int() with base 10: ''
Executed "ayesha (#32)" with final status error
```

It's crashing somewhere below `passSubJacobianRankTask()`, but it's unclear where.

**Comment by falquaddoomi** [comment]
Attempting to submit future jobs results in this:

```
Starting job 9...
 => Inside input processor!
Couldn't cast result 'MAXIMA>>' to an integer
Failed when executing the command 'rank(matrix([a_11, a_11**2, a_11*(a_11**2 + a_12*a_21 + a_13*a_31 + a_14*a_41), a_11*(a_11*(a_11**2 + a_12*a_21 + a_13*a_31 + a_14*a_41) + a_12*(a_11*a_21 + a_21*a_22 + a_23*a_31 + a_24*a_41) + a_13*(a_11*a_31 + a_21*a_32 + a_31*a_33 + a_34*a_41) + a_14*(a_11*a_41 + a_21*a_42 + a_31*a_43 + a_41*a_44))], [0, a_11*a_21, a_11*(a_11*a_21 + a_21*a_22 + a_23*a_31 + a_24*a_41), a_11*(a_21*(a_11**2 + a_12*a_21 + a_13*a_31 + a_14*a_41) + a_22*(a_11*a_21 + a_21*a_22 + a_23*a_31 + a_24*a_41) + a_23*(a_11*a_31 + a_21*a_32 + a_31*a_33 + a_34*a_41) + a_24*(a_11*a_41 + a_21*a_42 + a_31*a_43 + a_41*a_44))], [0, a_11*a_31, a_11*(a_11*a_31 + a_21*a_32 + a_31*a_33 + a_34*a_41), a_11*(a_31*(a_11**2 + a_12*a_21 + a_13*a_31 + a_14*a_41) + a_32*(a_11*a_21 + a_21*a_22 + a_23*a_31 + a_24*a_41) + a_33*(a_11*a_31 + a_21*a_32 + a_31*a_33 + a_34*a_41) + a_34*(a_11*a_41 + a_21*a_42 + a_31*a_43 + a_41*a_44))], [0, a_11*a_41, a_11*(a_11*a_41 + a_21*a_42 + a_31*a_43 + a_41*a_44), a_11*(a_41*(a_11**2 + a_12*a_21 + a_13*a_31 + a_14*a_41) + a_42*(a_11*a_21 + a_21*a_22 + a_23*a_31 + a_24*a_41) + a_43*(a_11*a_31 + a_21*a_32 + a_31*a_33 + a_34*a_41) + a_44*(a_11*a_41 + a_21*a_42 + a_31*a_43 + a_41*a_44))]));'
Traceback (most recent call last):
  File "/home/faisal/projects/disting/interface/management/commands/processor.py", line 101, in handle
    result = computation.main.processInput(job.makeInput(), notify=lambda x: logger_notify(x, job))
  File "/home/faisal/projects/disting/computation/main.py", line 90, in processInput
    myGraphModel = graphModel.graphModel(A, B, C, n, r, m, AdjMat, notify=notify)
  File "/home/faisal/projects/disting/computation/graphModel.py", line 31, in __init__
    (self.Q, self.QRank) = laplaceTools.calcQ(self.B, self.n, self.A)
  File "/home/faisal/projects/disting/computation/laplaceTools.py", line 119, in calcQ
    rank = calcRank(symQ)
  File "/home/faisal/projects/disting/computation/laplaceTools.py", line 351, in calcRank
    return maximaTools.getMatrixRank(in_mat)
  File "/home/faisal/projects/disting/computation/maximaTools.py", line 34, in getMatrixRank
    raise ex
ValueError: invalid literal for int() with base 10: 'MAXIMA>>'
Executed "TestingForLab8 (#9)" with final status error
```

**Comment by falquaddoomi** [comment]
Attempting to submit again results in this:

```
Executed "TestingForLab8 (#9)" with final status error
Starting job 9...
 => Inside input processor!
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54110)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/faisal/projects/disting/interface/glue/maxima_proxy.py", line 29, in handle
    self.request.sendall(calc_req.calc)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
----------------------------------------
```

After which the server enters an infinite loop of waiting for a real response from the server, despite having errored out earlier. It appears to be stuck in the loop at this line: https://github.com/falquaddoomi/disting/blob/master/interface/glue/maxima_proxy.py#L29.

Hypothesis: this issue is probably occurring because the exception handling is contained within the thread that communicates with the maxima server; the main process has no idea that the request didn't succeed, so it can't restart the connection or otherwise handle the failure.

**Comment by falquaddoomi** [comment]
Restarted the job processor, and job 9 still crashes (albeit, "amusingly", for a different reason); I anticipate future jobs will now crash as well:

```
Starting job 9...
 => Inside input processor!
 => completed laplaceTools.calcQ
 => completed laplaceTools.calcR
 => completed laplaceTools.calcTF
 => completed laplaceTools.getOrderedKeys
 => completed laplaceTools.calcJacobian
 => completed laplaceTools.calcRank
 => completed graphModel.graphModel
DONE MAKING ORIG MODEL
4
7
my original model graph (transposed)
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
my original model edges
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3)]
number of candidates: 11440
num of candidates left after graph properties checked: 1483 out of 11440
the alphas: [[0, 1, 2, 3, 4]]
the betas: [[0, 1, 2]]
num of candidates left alpha betas checked: 1483 out of 11440
Couldn't cast result 'Maxima encountered a Lisp error:' to an integer
Failed when executing the command 'rank(matrix([a_32*a_43, a_22*a_33 + a_22*a_43 + a_32*a_33 + a_32*a_43, a_33*a_41 + a_41*a_43, a_21*a_43 + a_33*a_41 + a_41*a_43, a_22*a_41 + a_32*a_41, a_21*a_32 + a_22*a_41 + a_32*a_41, 0], [0, a_22 + a_32 + a_33 + a_43, a_41, a_41, a_41, a_41, 0], [0, 1, 0, 0, 0, 0, 0], [a_33*a_34*(a_22 + a_32), a_33*a_34*(a_22 + a_32), a_33*a_34*(a_21 + a_41), a_33*a_34*(a_21 + a_41), a_34*(a_21*a_22 + a_21*a_32 + a_22*a_41 + a_32*a_41), 0, a_33*(a_21*a_22 + a_21*a_32 + a_22*a_41 + a_32*a_41)], [a_22*a_33 + a_22*a_34 + a_22*a_43 + a_32*a_33 + a_32*a_34 + a_32*a_43 + a_33*a_34, a_22*a_33 + a_22*a_34 + a_22*a_43 + a_32*a_33 + a_32*a_34 + a_32*a_43 + a_33*a_34, a_21*a_33 + a_21*a_34 + a_21*a_43 + a_33*a_34 + a_33*a_41 + a_34*a_41 + a_41*a_43, a_21*a_33 + a_21*a_34 + a_21*a_43 + a_33*a_34 + a_33*a_41 + a_34*a_41 + a_41*a_43, a_21*a_22 + a_21*a_32 + a_21*a_34 + a_22*a_34 + a_22*a_41 + a_32*a_34 + a_32*a_41 + a_34*a_41, a_21*a_22 + a_21*a_32 + a_22*a_41 + a_32*a_41, a_21*a_22 + a_21*a_32 + a_21*a_33 + a_22*a_33 + a_22*a_41 + a_32*a_33 + a_32*a_41 + a_33*a_41], [a_22 + a_32 + a_33 + a_34 + a_43, a_22 + a_32 + a_33 + a_34 + a_43, a_21 + a_33 + a_34 + a_41 + a_43, a_21 + a_33 + a_34 + a_41 + a_43, a_21 + a_22 + a_32 + a_34 + a_41, a_21 + a_22 + a_32 + a_41, a_21 + a_22 + a_32 + a_33 + a_41], [1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0]));'
Traceback (most recent call last):
  File "/home/faisal/projects/disting/interface/management/commands/processor.py", line 101, in handle
    result = computation.main.processInput(job.makeInput(), notify=lambda x: logger_notify(x, job))
  File "/home/faisal/projects/disting/computation/main.py", line 378, in processInput
    cand.calcJacobianRank()
  File "/home/faisal/projects/disting/computation/candidate.py", line 38, in calcJacobianRank
    self.Rank = maximaTools.getMatrixRank(self.Jac)
  File "/home/faisal/projects/disting/computation/maximaTools.py", line 34, in getMatrixRank
    raise ex
ValueError: invalid literal for int() with base 10: 'Maxima encountered a Lisp error:'
Executed "TestingForLab8 (#9)" with final status error
```

I think the solution is to remove the reliance on Maxima and this flimsy proxy system entirely.
